version: latest

services:
  partesql:
    build: ./partesql
    image: mysql/mysql-server:8.0.20
    restart: always
    
    environment:
      MYSQL_ROOT_PASSWORD: '123123'
      MYSQL_DATABASE: 'Livros'
      MYSQL_USER: 'root'
    ports:
      - '3306:3306'

  executavel:     
    image: python:3
    build: ./executavel
