version: latest

services:
  executavel:  
    image: python
    build: ./executavel/
    depends_on:
      - partesql

  partesql:
    image: mysql/mysql-server:8.0.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123
      MYSQL_DATABASE: 'Livros'
      MYSQL_USER: 'root'
